<?php

namespace Blog\LikeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesRepository extends EntityRepository
{
}
